#!/bin/sh

echo "START RESTORE ddbr FULL"

DISK=$(cat /proc/partitions | grep mmcblk0boot0)

if [ ! -z "$DISK" ] ; then
    DISK_PART="/dev/mmcblk0"
fi

DISK=$(cat /proc/partitions | grep mmcblk1boot0)

if [ ! -z "$DISK" ] ; then
    DISK_PART="/dev/mmcblk1"
fi

echo "Restore $DISK_PART"

dd if=/ddbr/emmc_full.img of=$DISK_PART conv=fsync bs=32M

echo "STOP RESTORE ddbr FULL"
