#!/bin/sh

echo "START ddBR 3G"

if [ ! -d /ddbr ] ; then
    mkdir /ddbr;chmod 777 /ddbr
fi

fdisk -l > /ddbr/fdisk_out_part_3g.txt

DISK=$(cat /proc/partitions | grep mmcblk0boot0)

if [ ! -z "$DISK" ] ; then
    DISK_PART="/dev/mmcblk0"
fi

DISK=$(cat /proc/partitions | grep mmcblk1boot0)

if [ ! -z "$DISK" ] ; then
    DISK_PART="/dev/mmcblk1"
fi

echo "Backup $DISK_PART"

dd if=$DISK_PART of=/ddbr/emmc_3g.img bs=32M count=100 conv=fsync

echo "STOP ddBR 3G"
